/*
 * JFormMaterial.java
 *
 * Created on 11 de enero de 2008, 0:00
 */

package vgestion;

import javax.swing.table.TableColumnModel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author  Juan Luis
 */
public class JFormFactura extends javax.swing.JDialog {
    private java.awt.Frame parent;
    private FacturaTableModel facturaTableModel;
    private Connection connection;

    public Connection getConnection() {
        return connection;
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
    }
    /** Creates new form JFormMaterial */
    public JFormFactura(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        this.parent = parent;
        facturaTableModel = new FacturaTableModel();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIdfactura = new javax.swing.JLabel();
        jtfIdfactura = new javax.swing.JTextField();
        jlIdproveedor = new javax.swing.JLabel();
        jtfIdproveedor = new javax.swing.JTextField();
        jlFechaDesde = new javax.swing.JLabel();
        jtfFechaDesdeDia = new javax.swing.JTextField();
        jtfFechaDesdeMes = new javax.swing.JTextField();
        jtfFechaDesdeAnio = new javax.swing.JTextField();
        jlFechaHasta = new javax.swing.JLabel();
        jtfFechaHastaDia = new javax.swing.JTextField();
        jtfFechaHastaMes = new javax.swing.JTextField();
        jtfFechaHastaAnio = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbMostrarHistorial = new javax.swing.JButton();
        jSPMaterial = new javax.swing.JScrollPane();
        jTMaterial = new javax.swing.JTable();

        setTitle("Facturas");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jlIdfactura.setText("Id Factura");

        jtfIdfactura.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIdfactura.setPreferredSize(new java.awt.Dimension(400, 20));

        jlIdproveedor.setText("Id Proveedor");

        jtfIdproveedor.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIdproveedor.setPreferredSize(new java.awt.Dimension(400, 20));

        jlFechaDesde.setText("Desde");

        jtfFechaDesdeDia.setColumns(2);

        jtfFechaDesdeMes.setColumns(2);

        jtfFechaDesdeAnio.setColumns(4);

        jlFechaHasta.setText("Hasta");

        jtfFechaHastaDia.setColumns(2);

        jtfFechaHastaMes.setColumns(2);

        jtfFechaHastaAnio.setColumns(4);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbMostrarHistorial.setText("Historial Factura");
        jbMostrarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarHistorialActionPerformed(evt);
            }
        });

        jTMaterial.setAutoCreateRowSorter(true);
        jTMaterial.setModel(facturaTableModel);
        jTMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMaterialMouseClicked(evt);
            }
        });
        jTMaterial.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTMaterialInputMethodTextChanged(evt);
            }
        });
        jSPMaterial.setViewportView(jTMaterial);
        //jTMaterial.getColumnModel().getColumn(0).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(1).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(2).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(3).setWidth(1000);
        //jTMaterial.updateUI();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jSPMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(432, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbEliminar)
                    .addComponent(jbEditar))
                .addGap(67, 67, 67))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlIdfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jtfIdfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlIdproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jtfFechaDesdeDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbBuscar)
                    .addGap(5, 5, 5)
                    .addComponent(jbNuevo)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jtfIdproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jtfFechaDesdeMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(368, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jtfFechaDesdeAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jlFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jtfFechaHastaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jtfFechaHastaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jtfFechaHastaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(416, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(400, Short.MAX_VALUE)
                    .addComponent(jbMostrarHistorial)
                    .addGap(57, 57, 57)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jSPMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jbEditar)
                .addGap(29, 29, 29)
                .addComponent(jbEliminar)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlIdfactura))
                        .addComponent(jtfIdfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addComponent(jlIdproveedor)
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlFechaDesde))
                        .addComponent(jtfFechaDesdeDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(201, 201, 201)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbBuscar)
                        .addComponent(jbNuevo))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addComponent(jtfIdproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(229, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jtfFechaDesdeMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(199, Short.MAX_VALUE)
                    .addComponent(jtfFechaDesdeAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(181, 181, 181)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(189, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlFechaHasta))
                        .addComponent(jtfFechaHastaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(171, 171, 171)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(jtfFechaHastaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(266, Short.MAX_VALUE)
                    .addComponent(jtfFechaHastaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(171, 171, 171)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(289, Short.MAX_VALUE)
                    .addComponent(jbMostrarHistorial)
                    .addGap(145, 145, 145)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int locX, locY, sizeX, sizeY;
        sizeX = 300;
        sizeY = 20;
        this.jlIdfactura.setSize(sizeX, sizeY);
        this.jlIdproveedor.setSize(sizeX, sizeY);
        this.jlFechaDesde.setSize(sizeX, sizeY);
        this.jlFechaHasta.setSize(sizeX, sizeY);
        
        
        this.jtfIdfactura.setSize(sizeX, sizeY);
        this.jtfIdproveedor.setSize(sizeX, sizeY);
        
        
        locX = 10;
        locY = 10;
        this.jlIdfactura.setLocation(locX, locY);
        locY+=this.jlIdfactura.getHeight();
        this.jlIdproveedor.setLocation(locX, locY);
        locY+=this.jlIdproveedor.getHeight();
        this.jlFechaDesde.setLocation(locX, locY);
        locY+=this.jlFechaDesde.getHeight();
        locY+=10;
        this.jbBuscar.setLocation(locX, locY); 
        locX = jbBuscar.getLocation().x + jbBuscar.getWidth()+10;
        this.jbNuevo.setLocation(locX, locY);
        locX += jbNuevo.getWidth()+10;
        this.jbEditar.setLocation(locX, locY);
        locX += jbEditar.getWidth()+10;
        this.jbEliminar.setLocation(locX, locY);
        locX += jbEliminar.getWidth()+10;
        this.jbMostrarHistorial.setLocation(locX, locY);
        locY+=this.jbBuscar.getHeight();
        
        locX = jbBuscar.getWidth()+20;
        locY = 10;
        this.jtfIdfactura.setLocation(locX, locY);
        locY+=this.jtfIdfactura.getHeight();
        this.jtfIdproveedor.setLocation(locX, locY);
        locY+=this.jtfIdproveedor.getHeight();
        this.jtfFechaDesdeDia.setLocation(locX, locY);
        locX += jtfFechaDesdeDia.getWidth() + 5;
        this.jtfFechaDesdeMes.setLocation(locX, locY);
        locX += jtfFechaDesdeMes.getWidth() + 5;
        this.jtfFechaDesdeAnio.setLocation(locX, locY);
        
        locX = jtfIdproveedor.getLocation().x + jtfIdproveedor.getWidth() - jtfFechaHastaAnio.getWidth();
        this.jtfFechaHastaAnio.setLocation(locX, locY);
        locX -= jtfFechaHastaMes.getWidth() + 5;
        this.jtfFechaHastaMes.setLocation(locX, locY);        
        locX -= jtfFechaHastaDia.getWidth() + 5;
        this.jtfFechaHastaDia.setLocation(locX, locY);
        locX -= jlFechaHasta.getPreferredSize().width + 10;
        this.jlFechaHasta.setLocation(locX, locY);
        
        
        locY=this.jbNuevo.getLocation().y + this.jbNuevo.getHeight();
        
        locX=10;
        locY+=10;
        this.jSPMaterial.setLocation(locX, locY);
        this.jSPMaterial.setSize(this.getWidth()-2*locX,this.getHeight()-locY-40);
        this.jTMaterial.getColumnModel().getColumn(0).setPreferredWidth(this.getWidth()/5);
        this.jTMaterial.getColumnModel().getColumn(1).setPreferredWidth(this.getWidth()/5);
        this.jTMaterial.getColumnModel().getColumn(2).setPreferredWidth(this.getWidth()/5);
        this.jTMaterial.getColumnModel().getColumn(3).setPreferredWidth(this.getWidth()/5);
        this.jTMaterial.getColumnModel().getColumn(4).setPreferredWidth(this.getWidth()/5);
        this.jTMaterial.getColumnModel().getColumn(0).sizeWidthToFit();  
    }//GEN-LAST:event_formComponentResized

    private void buscar() {
        String sql, sql2;
        Statement statement;
        ResultSet resultSet;
//        Albaran albaran;
        Factura factura;
        boolean noFecha;
        int diaDesde, mesDesde, anioDesde, diaHasta, mesHasta, anioHasta;

        facturaTableModel.clearTable();
        
        noFecha = jtfFechaDesdeDia.getText().trim().equals("") &&
                      jtfFechaDesdeMes.getText().trim().equals("") &&
                      jtfFechaDesdeAnio.getText().trim().equals("") &&
                      jtfFechaHastaDia.getText().trim().equals("") &&
                      jtfFechaHastaMes.getText().trim().equals("") &&
                      jtfFechaHastaAnio.getText().trim().equals("");
            
        if(!noFecha) {
            if(UtilGestion.getStringFecha(jtfFechaDesdeDia.getText().trim(), jtfFechaDesdeMes.getText().trim(), jtfFechaDesdeAnio.getText().trim())==null) {
////                System.out.println(jtfFechaDesdeDia.getText().trim()+"/"+jtfFechaDesdeMes.getText().trim()+"/"+jtfFechaDesdeAnio.getText().trim());
                javax.swing.JOptionPane.showMessageDialog(this, "Alguna de las fechas son incorrectas");
                return;
            }
            if(UtilGestion.getStringFecha(jtfFechaHastaDia.getText().trim(), jtfFechaHastaMes.getText().trim(), jtfFechaHastaAnio.getText().trim())==null) {
//                System.out.println(jtfFechaHastaDia.getText().trim()+"/"+jtfFechaHastaMes.getText().trim()+"/"+jtfFechaHastaAnio.getText().trim());
                javax.swing.JOptionPane.showMessageDialog(this, "Alguna de las fechas son incorrectas");
                return;
            }
        }
        
        sql2 = new String();
        if(!jtfIdfactura.getText().trim().equals("")) {
            sql2 += "ID_FACTURA LIKE '%" + jtfIdfactura.getText().trim() + "%'";
        }
        
        if(!jtfIdproveedor.getText().trim().equals("")) {
            if(!sql2.equals(""))
                sql2 += " AND ";
            sql2 += "ID_PROVEEDOR LIKE '%" + jtfIdproveedor.getText().trim() + "%'";
        }
        
        if(sql2.trim().equals(""))
            sql = "SELECT * FROM FACTURA;";
        else {
            sql = "SELECT * FROM FACTURA WHERE ";
            sql += sql2;
        }
        
        try {
            if(!noFecha) {
                diaDesde = Integer.parseInt(jtfFechaDesdeDia.getText().trim());
                mesDesde = Integer.parseInt(jtfFechaDesdeMes.getText().trim());
                anioDesde = Integer.parseInt(jtfFechaDesdeAnio.getText().trim());
                diaHasta = Integer.parseInt(jtfFechaHastaDia.getText().trim());
                mesHasta = Integer.parseInt(jtfFechaHastaMes.getText().trim());
                anioHasta = Integer.parseInt(jtfFechaHastaAnio.getText().trim());
            } else {
                diaDesde = 0;
                mesDesde = 0;
                anioDesde = 0;
                diaHasta = 0;
                mesHasta = 0;
                anioHasta = 0;
            }
                
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while(resultSet.next()) {
                factura = new Factura();
                factura.setId_factura(resultSet.getString("ID_FACTURA"));
                factura.setId_proveedor(resultSet.getString("ID_PROVEEDOR"));
                factura.setTotalNeto(Factura.getTotalNeto(connection, factura.getId_proveedor(), factura.getId_factura()));
                factura.setDia(resultSet.getInt("DIA"));
                factura.setMes(resultSet.getInt("MES"));
                factura.setAnio(resultSet.getInt("ANIO"));
                if(noFecha || factura.isInFecha(diaDesde, mesDesde, anioDesde, diaHasta, mesHasta, anioHasta)) {
                    facturaTableModel.addFactura(factura);
                }
            }
            jTMaterial.updateUI();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    
    private void jTMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMaterialMouseClicked
//        this.jTMaterial.getCellEditor(WIDTH, WIDTH);
//        System.out.println(this.jTMaterial.columnAtPoint(evt.getPoint()));
    }//GEN-LAST:event_jTMaterialMouseClicked

    private void jTMaterialInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTMaterialInputMethodTextChanged
//        System.out.println("");
    }//GEN-LAST:event_jTMaterialInputMethodTextChanged

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        JFormFacturaEditor jFormFacturaEditor = new JFormFacturaEditor(parent,true);
        jFormFacturaEditor.setConnection(connection);
        jFormFacturaEditor.setNewFactura(true);
        jFormFacturaEditor.setVisible(true);
        this.jTMaterial.updateUI();
}//GEN-LAST:event_jbNuevoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        Factura factura;
        int row;
        JFormFacturaEditor jFormFacturaEditor = new JFormFacturaEditor(parent,true);
        
        
        row = jTMaterial.getSelectedRow();
        row = jTMaterial.convertRowIndexToModel(row);
        factura = facturaTableModel.getFactura(row);
        if(factura!=null) {
            jFormFacturaEditor.setConnection(connection);
            jFormFacturaEditor.setFactura(factura);
            jFormFacturaEditor.setNewFactura(false);
            jFormFacturaEditor.setVisible(true);
            buscar();
            this.jTMaterial.updateUI();
        } else {
            JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada");
        }        
}//GEN-LAST:event_jbEditarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        Factura factura;
        int row;
        int option;
        String sql;
        Statement statement;
        
        
        row = jTMaterial.getSelectedRow();
        factura = facturaTableModel.getFactura(row);
        if(factura!=null) {
            option = javax.swing.JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar la factura?");
            if(option == javax.swing.JOptionPane.YES_OPTION) {
                sql = "DELETE FROM ALBARAN_FACTURA WHERE ID_PROVEEDOR='" +
                      factura.getId_proveedor() +
                      "' AND ID_FACTURA='" +
                      factura.getId_factura() +
                      "';";
                try {
                    statement = connection.createStatement();
                    statement.executeUpdate(sql);
                    sql = "DELETE FROM FACTURA WHERE ID_PROVEEDOR='" +
                          factura.getId_proveedor() +
                          "' AND ID_FACTURA='" +
                          factura.getId_factura() +
                          "';";
                    statement.executeUpdate(sql);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            buscar();
            this.jTMaterial.updateUI();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada");
        } 
}//GEN-LAST:event_jbEliminarActionPerformed

    private void jbMostrarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarHistorialActionPerformed
          JFormHistorialFactura jFormHistorialFactura;
          int row;
          Factura factura;         
          
          row = jTMaterial.getSelectedRow();
          if(row<0)
              return;
          row = jTMaterial.convertRowIndexToModel(row);
        
          factura = facturaTableModel.getFactura(row);
          
          jFormHistorialFactura = new JFormHistorialFactura(null, true);
          jFormHistorialFactura.setConnection(connection);
          jFormHistorialFactura.setFactura(factura);
          jFormHistorialFactura.setVisible(true);
          
          
          
          
        
//        String sql1,sql2;
//        int row;
//        Factura factura;
//        Statement statement;
//        ResultSet rs1,rs2;
//        String idAlbaran, idMaterial;
//        Vector vIdMaterial;
//        
//        row = jTMaterial.getSelectedRow();
//        row = jTMaterial.convertRowIndexToModel(row);
//        
//        factura = facturaTableModel.getFactura(row);
//        
//        sql1 = "SELECT * FROM FACTURA WHERE ID_FACTURA='"+
//               factura.getId_factura() +
//               "', ID_PROVEEDOR='"+
//               factura.getId_proveedor()+
//               "';";
//        try {
//            statement = connection.createStatement();
//            rs1 = statement.executeQuery(sql1);
//            vIdMaterial = new Vector();
//            while(rs1.next()) {
//                idAlbaran = rs1.getString("ID_ALBARAN");
//                sql2 = "SELECT * MATERIAL_ALBARAN WHERE ID_PROVEEDOR='"+
//                       factura.getId_proveedor()+
//                       "', ID_ALBARAN='"+
//                       idAlbaran+
//                       "';";
//                rs2 = statement.executeQuery(sql2);
//                while(rs2.next()) {
//                    idMaterial = rs2.getString("ID_MATERIAL");
//                    if(isIdMaterialInVector(vIdMaterial,idMaterial))
//                        vIdMaterial.addElement(idMaterial);
//                }
//            }
//        }catch(Exception ex) {
//            ex.printStackTrace();
//        }
               
}//GEN-LAST:event_jbMostrarHistorialActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormFactura(null,true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jSPMaterial;
    private javax.swing.JTable jTMaterial;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbMostrarHistorial;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JLabel jlFechaDesde;
    private javax.swing.JLabel jlFechaHasta;
    private javax.swing.JLabel jlIdfactura;
    private javax.swing.JLabel jlIdproveedor;
    private javax.swing.JTextField jtfFechaDesdeAnio;
    private javax.swing.JTextField jtfFechaDesdeDia;
    private javax.swing.JTextField jtfFechaDesdeMes;
    private javax.swing.JTextField jtfFechaHastaAnio;
    private javax.swing.JTextField jtfFechaHastaDia;
    private javax.swing.JTextField jtfFechaHastaMes;
    private javax.swing.JTextField jtfIdfactura;
    private javax.swing.JTextField jtfIdproveedor;
    // End of variables declaration//GEN-END:variables
    
}
