/*
 * JFormAlbaranFactura.java
 *
 * Created on 9 de noviembre de 2008, 11:00
 */

package vgestion;

import java.sql.*;
import java.util.Vector;

/**
 *
 * @author  juanlu
 */
public class JFormAlbaranFactura extends javax.swing.JDialog {
    private Connection connection;
    
    /** Creates new form JFormAlbaranFactura */
    public JFormAlbaranFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jlIdAlbaran = new javax.swing.JLabel();
        jtfIdAlbaran = new javax.swing.JTextField();
        jlIdProveedor = new javax.swing.JLabel();
        jtfIdProveedor = new javax.swing.JTextField();
        jlProveedor = new javax.swing.JLabel();
        jtfProveedor = new javax.swing.JTextField();
        jpanelFactura = new javax.swing.JPanel();
        jspFactura = new javax.swing.JScrollPane();
        jlistFactura = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturas del albaran");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jlIdAlbaran.setText("Id Albaran");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jlIdAlbaran, gridBagConstraints);

        jtfIdAlbaran.setEnabled(false);
        jtfIdAlbaran.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jtfIdAlbaran, gridBagConstraints);

        jlIdProveedor.setText("Id Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jlIdProveedor, gridBagConstraints);

        jtfIdProveedor.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jtfIdProveedor, gridBagConstraints);

        jlProveedor.setText("Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jlProveedor, gridBagConstraints);

        jtfProveedor.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jtfProveedor, gridBagConstraints);

        jpanelFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Facturas"));
        jpanelFactura.setLayout(new java.awt.BorderLayout());

        jlistFactura.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "adaads", "adaadsddd" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jspFactura.setViewportView(jlistFactura);

        jpanelFactura.add(jspFactura, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jpanelFactura, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFormAlbaranFactura dialog = new JFormAlbaranFactura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
    }
    
    
    
    public void setAlbaran(Albaran albaran) {
        Statement statement;
        ResultSet resultSet;
        String sql;
        Vector vFactura;
        AlbaranFacturaListModel albaranFacturaListModel;
        
        jtfIdAlbaran.setText(albaran.getId_albaran());
        jtfIdProveedor.setText(albaran.getId_proveedor());
        
        
        
        try {
            sql = "SELECT * FROM PROVEEDOR WHERE ID_PROVEEDOR='" +
                  albaran.getId_proveedor() +
                  "';";
            System.out.println(sql);
            
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            if(!resultSet.next()) {
                dispose();
                return;
            }
                 
            jtfProveedor.setText(resultSet.getString("NOMBRE"));
            
            
            sql = "SELECT * FROM ALBARAN_FACTURA WHERE ID_PROVEEDOR='" +
                  albaran.getId_proveedor() +
                  "' AND ID_ALBARAN = '" +
                  albaran.getId_albaran() +
                  "';";
            
            System.out.println(sql);
            
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            
            
            vFactura = new Vector();
            
            
            while(resultSet.next()) {
                vFactura.addElement(resultSet.getString("ID_FACTURA"));
            }
            
            albaranFacturaListModel = new AlbaranFacturaListModel(vFactura);
            
            jlistFactura.setModel(albaranFacturaListModel);
            jlistFactura.updateUI();
                
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlIdAlbaran;
    private javax.swing.JLabel jlIdProveedor;
    private javax.swing.JLabel jlProveedor;
    private javax.swing.JList jlistFactura;
    private javax.swing.JPanel jpanelFactura;
    private javax.swing.JScrollPane jspFactura;
    private javax.swing.JTextField jtfIdAlbaran;
    private javax.swing.JTextField jtfIdProveedor;
    private javax.swing.JTextField jtfProveedor;
    // End of variables declaration//GEN-END:variables
    
}
