/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vgestion;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author lion
 */
public class JFormProveedorEditor extends javax.swing.JDialog {
    private Connection connection;
    /**
     * Creates new form JFormProveedorEditor
     */
    public JFormProveedorEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Connection getConnection() {
        return connection;
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lCif = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlDirection = new javax.swing.JLabel();
        jlLocation = new javax.swing.JLabel();
        jlCp = new javax.swing.JLabel();
        jlTelephone = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jtfCif = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jtfDirection = new javax.swing.JTextField();
        jtfLocation = new javax.swing.JTextField();
        jtfCp = new javax.swing.JTextField();
        jtfTelephone = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jbOk = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Nuevo proveedor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 300));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel1.setLayout(new java.awt.BorderLayout(50, 10));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel2.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel3.setLayout(new java.awt.GridLayout(6, 1, 5, 5));

        lCif.setText("CIF: *");
        lCif.setMaximumSize(new java.awt.Dimension(100, 15));
        lCif.setMinimumSize(new java.awt.Dimension(100, 15));
        lCif.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(lCif);

        jlName.setText("Nombre");
        jlName.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(jlName);

        jlDirection.setText("Dirección:");
        jlDirection.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(jlDirection);

        jlLocation.setText("Población:");
        jlLocation.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(jlLocation);

        jlCp.setText("CP:");
        jlCp.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(jlCp);

        jlTelephone.setText("Teléfono");
        jPanel3.add(jlTelephone);

        jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setPreferredSize(new java.awt.Dimension(20, 100));
        jPanel4.setLayout(new java.awt.GridLayout(6, 1, 5, 5));

        jtfCif.setMaximumSize(new java.awt.Dimension(20, 10));
        jtfCif.setMinimumSize(new java.awt.Dimension(20, 10));
        jtfCif.setPreferredSize(new java.awt.Dimension(20, 10));
        jPanel4.add(jtfCif);
        jPanel4.add(jtfName);
        jPanel4.add(jtfDirection);
        jPanel4.add(jtfLocation);
        jPanel4.add(jtfCp);
        jPanel4.add(jtfTelephone);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        jbOk.setText("Aceptar");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });
        jPanel5.add(jbOk);

        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jPanel5.add(jbCancel);

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(26, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        String sql;
        Statement statement ;
        ResultSet resultSet;
        
        
        sql = "SELECT * FROM PROVEEDOR WHERE CIF = '" +
              jtfCif.getText().trim() +
              "';";
        
        try {
            statement = this.connection.createStatement();
            resultSet = statement.executeQuery(sql);
            if(resultSet.next()) {
                javax.swing.JOptionPane.showMessageDialog(this,"El proveedor ya existe");
                return;
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Database error");
            return;
        }
        
        if(jtfCif.getText().trim().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,"El CIF no puede estar vacío");
            return;
        }
        
        if(jtfName.getText().trim().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,"El nombre no puede estar vacío");
            return;
        }
        
        sql =  "INSERT INTO PROVEEDOR (ID_PROVEEDOR,";
        sql += " CIF,";
        sql += " NOMBRE,";
        sql += " DIRECCION,";
        sql += " POBLACION,";
        sql += " CP,";
        sql += " TELEFONO) VALUES (";
        sql += "'" + this.jtfCif.getText().trim();
        sql += "' , '" + this.jtfCif.getText().trim();
        sql += "' , '" + this.jtfName.getText().trim();
        sql += "' , '" + this.jtfDirection.getText().trim();      
        sql += "' , '" + this.jtfLocation.getText().trim();               
        sql += "' , '" + this.jtfCp.getText().trim();
        sql += "' , '" + this.jtfTelephone.getText().trim();
        sql += "');";
        
        try {
            statement = this.connection.createStatement();
            if(statement.executeUpdate(sql)<0) {
                javax.swing.JOptionPane.showMessageDialog(this,"No insertado");
//                System.out.println(sql);
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,"Database error 2");
//            System.out.println(sql);
            return;
        }
        
        this.dispose();
    }//GEN-LAST:event_jbOkActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormProveedorEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormProveedorEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormProveedorEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormProveedorEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFormProveedorEditor dialog = new JFormProveedorEditor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOk;
    private javax.swing.JLabel jlCp;
    private javax.swing.JLabel jlDirection;
    private javax.swing.JLabel jlLocation;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlTelephone;
    private javax.swing.JTextField jtfCif;
    private javax.swing.JTextField jtfCp;
    private javax.swing.JTextField jtfDirection;
    private javax.swing.JTextField jtfLocation;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfTelephone;
    private javax.swing.JLabel lCif;
    // End of variables declaration//GEN-END:variables
}
