/*
 * JFormMaterial.java
 *
 * Created on 11 de enero de 2008, 0:00
 */

package vgestion;

import vgestion.*;
import javax.swing.table.TableColumnModel;
import java.sql.*;
import java.util.*;

/**
 *
 * @author  Juan Luis
 */
public class JFormHistorialFactura extends javax.swing.JDialog {
    private java.awt.Frame parent;
    private HistorialFacturaTableModel historialFacturaTableModel;
    private Connection connection;
    private String id_factura;
    private String id_proveedor;
    private Factura factura;

    public Factura getFactura() {
        return factura;
    }

    public void setFactura(Factura factura) {
        this.factura = factura;
        setId_factura(factura.getId_factura());
        setId_proveedor(factura.getId_proveedor());
    }
    
    public String getId_factura() {
        return id_factura;
    }

    public void setId_factura(String id_factura) {
        this.id_factura = id_factura;
        jtfIfactura.setText(id_factura);
        jtfIfactura.setEnabled(true);
    }

    public String getId_proveedor() {
        return id_proveedor;
    }

    public void setId_proveedor(String id_proveedor) {
        this.id_proveedor = id_proveedor;
        jtfIdproveedor.setText(id_proveedor);
        jtfIdproveedor.setEnabled(true);
    }
    
    public Connection getConnection() {
        return connection;
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
    }
    
    public void setMaterial(String id_material, String id_proveedor) {
        jtfIfactura.setText(id_material);
        jtfIdproveedor.setText(id_proveedor);
        jtfIfactura.setEnabled(false);
        jtfIdproveedor.setEnabled(false);
        buscar();
        
    }
    
    
    /** Creates new form JFormMaterial */
    public JFormHistorialFactura(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        this.parent = parent;
        historialFacturaTableModel = new HistorialFacturaTableModel();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIdfactura = new javax.swing.JLabel();
        jtfIfactura = new javax.swing.JTextField();
        jlIdproveedor = new javax.swing.JLabel();
        jtfIdproveedor = new javax.swing.JTextField();
        jlFechaDesde = new javax.swing.JLabel();
        jtfFechaDesdeDia = new javax.swing.JTextField();
        jtfFechaDesdeMes = new javax.swing.JTextField();
        jtfFechaDesdeAnio = new javax.swing.JTextField();
        jlFechaHasta = new javax.swing.JLabel();
        jtfFechaHastaDia = new javax.swing.JTextField();
        jtfFechaHastaMes = new javax.swing.JTextField();
        jtfFechaHastaAnio = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jSPMaterial = new javax.swing.JScrollPane();
        jTMaterial = new javax.swing.JTable();

        setTitle("Historial factura");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jlIdfactura.setText("Id Material");

        jtfIfactura.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIfactura.setPreferredSize(new java.awt.Dimension(400, 20));

        jlIdproveedor.setText("Id Proveedor");

        jtfIdproveedor.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIdproveedor.setPreferredSize(new java.awt.Dimension(400, 20));

        jlFechaDesde.setText("Desde");

        jtfFechaDesdeDia.setColumns(2);

        jtfFechaDesdeMes.setColumns(2);

        jtfFechaDesdeAnio.setColumns(4);

        jlFechaHasta.setText("Hasta");

        jtfFechaHastaDia.setColumns(2);

        jtfFechaHastaMes.setColumns(2);

        jtfFechaHastaAnio.setColumns(4);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jTMaterial.setModel(historialFacturaTableModel);
        jTMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMaterialMouseClicked(evt);
            }
        });
        jTMaterial.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTMaterialInputMethodTextChanged(evt);
            }
        });
        jSPMaterial.setViewportView(jTMaterial);
        //jTMaterial.getColumnModel().getColumn(0).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(1).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(2).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(3).setWidth(1000);
        //jTMaterial.updateUI();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jSPMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlIdfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jtfIfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlIdproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jtfFechaDesdeDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbBuscar)
                    .addGap(265, 265, 265)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jtfIdproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jtfFechaDesdeMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(368, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jtfFechaDesdeAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jlFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jtfFechaHastaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jtfFechaHastaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jtfFechaHastaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(416, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jSPMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlIdfactura))
                        .addComponent(jtfIfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addComponent(jlIdproveedor)
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlFechaDesde))
                        .addComponent(jtfFechaDesdeDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(201, 201, 201)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbBuscar)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addComponent(jtfIdproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(229, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jtfFechaDesdeMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(199, Short.MAX_VALUE)
                    .addComponent(jtfFechaDesdeAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(181, 181, 181)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(189, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlFechaHasta))
                        .addComponent(jtfFechaHastaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(171, 171, 171)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(jtfFechaHastaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(266, Short.MAX_VALUE)
                    .addComponent(jtfFechaHastaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(171, 171, 171)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int locX, locY, sizeX, sizeY;
        sizeX = 300;
        sizeY = 20;
        this.jlIdfactura.setSize(sizeX, sizeY);
        this.jlIdproveedor.setSize(sizeX, sizeY);
        this.jlFechaDesde.setSize(sizeX, sizeY);
        this.jlFechaHasta.setSize(sizeX, sizeY);
        
        this.jtfIfactura.setSize(sizeX, sizeY);
        this.jtfIdproveedor.setSize(sizeX, sizeY);
        
        locX = 10;
        locY = 10;
        this.jlIdfactura.setLocation(locX, locY);
        locY+=this.jlIdfactura.getHeight();
        this.jlIdproveedor.setLocation(locX, locY);
        locY+=this.jlIdproveedor.getHeight();
        this.jlFechaDesde.setLocation(locX, locY);
        locY+=this.jlFechaDesde.getHeight();
        locY+=10;
        this.jbBuscar.setLocation(locX, locY);
        locY+=this.jbBuscar.getHeight();
        
        
        locX = jbBuscar.getWidth()+20;
        locY = 10;
        this.jtfIfactura.setLocation(locX, locY);
        locY+=this.jtfIfactura.getHeight();
        this.jtfIdproveedor.setLocation(locX, locY);
        locY+=this.jtfIdproveedor.getHeight();
        this.jtfFechaDesdeDia.setLocation(locX, locY);
        locX += jtfFechaDesdeDia.getWidth() + 5;
        this.jtfFechaDesdeMes.setLocation(locX, locY);
        locX += jtfFechaDesdeMes.getWidth() + 5;
        this.jtfFechaDesdeAnio.setLocation(locX, locY);
        
        
        
        locX = jtfIdproveedor.getLocation().x + jtfIdproveedor.getWidth() - jtfFechaHastaAnio.getWidth();
        this.jtfFechaHastaAnio.setLocation(locX, locY);
        locX -= jtfFechaHastaMes.getWidth() + 5;
        this.jtfFechaHastaMes.setLocation(locX, locY);        
        locX -= jtfFechaHastaDia.getWidth() + 5;
        this.jtfFechaHastaDia.setLocation(locX, locY);
        locX -= jlFechaHasta.getPreferredSize().width + 10;
        this.jlFechaHasta.setLocation(locX, locY);
        
        locX = 10;
                
        locY+=this.jtfFechaDesdeDia.getHeight();
        locY+=10;
        this.jbBuscar.setLocation(locX, locY);
        locY+=this.jbBuscar.getHeight();
        
        locX=10;
        locY+=10;
        this.jSPMaterial.setLocation(locX, locY);
        this.jSPMaterial.setSize(this.getWidth()-2*locX,this.getHeight()-locY-40);
        this.jTMaterial.getColumnModel().getColumn(0).setPreferredWidth(100);
        this.jTMaterial.getColumnModel().getColumn(1).setPreferredWidth(100);
        this.jTMaterial.getColumnModel().getColumn(2).setPreferredWidth(100);
        this.jTMaterial.getColumnModel().getColumn(3).setPreferredWidth(this.getWidth()-700);
        this.jTMaterial.getColumnModel().getColumn(4).setPreferredWidth(100);
//        this.jTMaterial.getColumnModel().getColumn(5).setPreferredWidth(100);
//        this.jTMaterial.getColumnModel().getColumn(6).setPreferredWidth(100);
//        this.jTMaterial.getColumnModel().getColumn(7).setPreferredWidth(100);
//        this.jTMaterial.getColumnModel().getColumn(0).sizeWidthToFit();
    }//GEN-LAST:event_formComponentResized

    private void jTMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMaterialMouseClicked
//        this.jTMaterial.getCellEditor(WIDTH, WIDTH);
//        System.out.println(this.jTMaterial.columnAtPoint(evt.getPoint()));
    }//GEN-LAST:event_jTMaterialMouseClicked

    private void jTMaterialInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTMaterialInputMethodTextChanged
//        System.out.println("");
    }//GEN-LAST:event_jTMaterialInputMethodTextChanged

    public void buscar() {
        int diaHasta, mesHasta, anioHasta;
        int diaDesde, mesDesde, anioDesde;
        boolean noFecha;
        String sql1,sql2,sql3,sql4;
        Statement statement;
        ResultSet rs1,rs2,rs3,rs4;
        String idAlbaran, idMaterial;
        Vector vIdMaterial, vIdAlbaran;
        HistorialMaterial historialMaterial;
        
        sql1 = "SELECT * FROM ALBARAN_FACTURA WHERE ID_FACTURA='"+
               factura.getId_factura() +
               "' AND ID_PROVEEDOR='"+
               factura.getId_proveedor()+
               "';";
//        System.out.println(sql1);
        historialFacturaTableModel.clearTable();
        try {
            vIdMaterial = new Vector();
            statement = connection.createStatement();
            rs1 = statement.executeQuery(sql1);
            vIdAlbaran = new Vector();
            while(rs1.next()) {
                vIdAlbaran.addElement(rs1.getString("ID_ALBARAN"));
            }
//            System.out.println("PASO 1");
            for(int i=0;i<vIdAlbaran.size();i++) {
                sql2 = "SELECT * FROM MATERIAL_ALBARAN WHERE ID_PROVEEDOR='"+
                       factura.getId_proveedor().trim()+
                       "' AND ID_ALBARAN='"+
                       (String)vIdAlbaran.elementAt(i)+
                       "';";
                rs2 = statement.executeQuery(sql2);
                while(rs2.next()) {
                    idMaterial = rs2.getString("ID_MATERIAL");
//                    System.out.println(idMaterial);
                    if(!isIdMaterialInVector(vIdMaterial,idMaterial))
                        vIdMaterial.addElement(idMaterial);
                }
            }
//            System.out.println("PASO 2");
            noFecha = jtfFechaDesdeDia.getText().trim().equals("") &&
                      jtfFechaDesdeMes.getText().trim().equals("") &&
                      jtfFechaDesdeAnio.getText().trim().equals("") &&
                      jtfFechaHastaDia.getText().trim().equals("") &&
                      jtfFechaHastaMes.getText().trim().equals("") &&
                      jtfFechaHastaAnio.getText().trim().equals("");
            
            diaHasta = 0;
            mesHasta = 0;
            anioHasta = 0;
            
            diaDesde = 0;
            mesDesde = 0;
            anioDesde = 0;
            
            if(!noFecha) {
                if(UtilGestion.getStringFecha(jtfFechaDesdeDia.getText().trim(), jtfFechaDesdeMes.getText().trim(), jtfFechaDesdeAnio.getText().trim())==null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Alguna de las fechas son incorrectas");
                    return;
                }
                if(UtilGestion.getStringFecha(jtfFechaHastaDia.getText().trim(), jtfFechaHastaMes.getText().trim(), jtfFechaHastaAnio.getText().trim())==null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Alguna de las fechas son incorrectas");
                    return;
                }
                diaHasta = Integer.parseInt(jtfFechaHastaDia.getText().trim());
                mesHasta = Integer.parseInt(jtfFechaHastaMes.getText().trim());
                anioHasta = Integer.parseInt(jtfFechaHastaAnio.getText().trim());

                diaDesde = Integer.parseInt(jtfFechaDesdeDia.getText().trim());
                mesDesde = Integer.parseInt(jtfFechaDesdeMes.getText().trim());
                anioDesde = Integer.parseInt(jtfFechaDesdeAnio.getText().trim());
            }
            
            for(int i=0;i<vIdMaterial.size();i++) {
                Material material;
                
//                System.out.println((String)vIdMaterial.elementAt(i));
                
                sql4 = "SELECT * FROM MATERIAL WHERE ID_MATERIAL='"+
                        (String)vIdMaterial.elementAt(i)+
                        "' AND ID_PROVEEDOR='" +
                        this.jtfIdproveedor.getText().trim() +
                        "';";
                rs4 = statement.executeQuery(sql4); 
                if(!rs4.next()) {
//                    System.out.println(sql4);
                    return;
                }
                material = new Material();
                material.setId_material((String)vIdMaterial.elementAt(i));
                material.setId_proveedor(this.jtfIdproveedor.getText().trim());
                material.setCategoria(rs4.getString("CATEGORIA"));
                material.setDescripcion(rs4.getString("DESCRIPCION"));
                material.setMarca(rs4.getString("MARCA"));
                material.setRef_marca(rs4.getString("REF_MARCA"));
                
                
                sql3 = "SELECT * FROM MATERIAL_ALBARAN WHERE ID_MATERIAL='" +
                        (String)vIdMaterial.elementAt(i) +
                        "' AND ID_PROVEEDOR='" +
                        this.jtfIdproveedor.getText().trim() +
                        "' ORDER BY ID_ALBARAN;";
                
                rs3 = statement.executeQuery(sql3);
                
                while(rs3.next()) {
//                    System.out.println(rs3.getString("ID_ALBARAN"));
                    historialMaterial = new HistorialMaterial();
                    historialMaterial.setMaterial(material);
                    historialMaterial.setId_albaran(rs3.getString("ID_ALBARAN"));
                    historialMaterial.setCantidad(rs3.getDouble("CANTIDAD"));
                    historialMaterial.setPrecio(rs3.getDouble("PRECIO"));
                    historialMaterial.setDescuento(rs3.getDouble("DESCUENTO"));
                    historialMaterial.setRaee(rs3.getDouble("RAEE"));
                    historialMaterial.setId_proveedor(jtfIdproveedor.getText().trim());
                    historialMaterial.setConnection(connection);
                    historialMaterial.updateFecha();
                   
                    if(noFecha || historialMaterial.isInFecha(diaDesde, mesDesde, anioDesde, diaHasta, mesHasta, anioHasta)) {
//                        historialMaterial.addHistorialMaterial(historialMaterial);
                    }
                }
                
                
                
                jTMaterial.updateUI();
            }
//            System.out.println("PASO 3");
            
        }catch(Exception ex) {
            ex.printStackTrace();
        }
        
    }
    
    private boolean isIdMaterialInVector(Vector vIdMaterial, String idMaterial) {
        String id;
        for(int i=0;i<vIdMaterial.size();i++){
            id = (String)vIdMaterial.elementAt(i);
            if(id.trim().equals(idMaterial.trim()))
                return true;
        }
        return false;
    }
    
    
    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_jbBuscarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormHistorialFactura(null,true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jSPMaterial;
    private javax.swing.JTable jTMaterial;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JLabel jlFechaDesde;
    private javax.swing.JLabel jlFechaHasta;
    private javax.swing.JLabel jlIdfactura;
    private javax.swing.JLabel jlIdproveedor;
    private javax.swing.JTextField jtfFechaDesdeAnio;
    private javax.swing.JTextField jtfFechaDesdeDia;
    private javax.swing.JTextField jtfFechaDesdeMes;
    private javax.swing.JTextField jtfFechaHastaAnio;
    private javax.swing.JTextField jtfFechaHastaDia;
    private javax.swing.JTextField jtfFechaHastaMes;
    private javax.swing.JTextField jtfIdproveedor;
    private javax.swing.JTextField jtfIfactura;
    // End of variables declaration//GEN-END:variables
    
}
