/*
 * JFormMaterial.java
 *
 * Created on 11 de enero de 2008, 0:00
 */

package vgestion;

import javax.swing.table.TableColumnModel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Vector;

/**
 *
 * @author  Juan Luis
 */
public class JFormAlbaran extends javax.swing.JDialog {
    private java.awt.Frame parent;
    private AlbaranTableModel albaranTableModel;
    private Connection connection;

    public Connection getConnection() {
        return connection;
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
        albaranTableModel.setConnection(connection);
    }
    /** Creates new form JFormMaterial */
    public JFormAlbaran(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        this.parent = parent;
        albaranTableModel = new AlbaranTableModel();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMostrar = new javax.swing.ButtonGroup();
        jlIdalbaran = new javax.swing.JLabel();
        jtfIdalbaran = new javax.swing.JTextField();
        jlIdproveedor = new javax.swing.JLabel();
        jtfIdproveedor = new javax.swing.JTextField();
        jlFechaDesde = new javax.swing.JLabel();
        jtfFechaDesdeDia = new javax.swing.JTextField();
        jtfFechaDesdeMes = new javax.swing.JTextField();
        jtfFechaDesdeAnio = new javax.swing.JTextField();
        jlFechaHasta = new javax.swing.JLabel();
        jtfFechaHastaDia = new javax.swing.JTextField();
        jtfFechaHastaMes = new javax.swing.JTextField();
        jtfFechaHastaAnio = new javax.swing.JTextField();
        jlObra = new javax.swing.JLabel();
        jtfObra = new javax.swing.JTextField();
        jlReceptor = new javax.swing.JLabel();
        jtfReceptor = new javax.swing.JTextField();
        jpanelMostrar = new javax.swing.JPanel();
        jrbMostrarTodos = new javax.swing.JRadioButton();
        jrbMostrarFacturados = new javax.swing.JRadioButton();
        jrbMostrarNoFacturados = new javax.swing.JRadioButton();
        jrbMostrarFacturados1Vez = new javax.swing.JRadioButton();
        jrbMostrarFacturadosMasVeces = new javax.swing.JRadioButton();
        jbBuscar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSustituir = new javax.swing.JButton();
        jbFacturar = new javax.swing.JButton();
        jbBuscarFactura = new javax.swing.JButton();
        jSPMaterial = new javax.swing.JScrollPane();
        jTMaterial = new javax.swing.JTable();

        setTitle("Albaranes");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jlIdalbaran.setText("Id Albarán");

        jtfIdalbaran.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIdalbaran.setPreferredSize(new java.awt.Dimension(400, 20));

        jlIdproveedor.setText("Id Proveedor");

        jtfIdproveedor.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIdproveedor.setPreferredSize(new java.awt.Dimension(400, 20));

        jlFechaDesde.setText("Desde");

        jtfFechaDesdeDia.setColumns(2);

        jtfFechaDesdeMes.setColumns(2);

        jtfFechaDesdeAnio.setColumns(4);

        jlFechaHasta.setText("Hasta");

        jtfFechaHastaDia.setColumns(2);

        jtfFechaHastaMes.setColumns(2);

        jtfFechaHastaAnio.setColumns(4);

        jlObra.setText("Obra");

        jtfObra.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfObra.setPreferredSize(new java.awt.Dimension(400, 20));

        jlReceptor.setText("Receptor");

        jtfReceptor.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfReceptor.setPreferredSize(new java.awt.Dimension(400, 20));

        jpanelMostrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar"));

        buttonGroupMostrar.add(jrbMostrarTodos);
        jrbMostrarTodos.setSelected(true);
        jrbMostrarTodos.setText("Todos");
        jpanelMostrar.add(jrbMostrarTodos);

        buttonGroupMostrar.add(jrbMostrarFacturados);
        jrbMostrarFacturados.setText("Facturados");
        jpanelMostrar.add(jrbMostrarFacturados);

        buttonGroupMostrar.add(jrbMostrarNoFacturados);
        jrbMostrarNoFacturados.setText("No facturados");
        jpanelMostrar.add(jrbMostrarNoFacturados);

        buttonGroupMostrar.add(jrbMostrarFacturados1Vez);
        jrbMostrarFacturados1Vez.setText("Facturados 1 vez");
        jpanelMostrar.add(jrbMostrarFacturados1Vez);

        buttonGroupMostrar.add(jrbMostrarFacturadosMasVeces);
        jrbMostrarFacturadosMasVeces.setText("Facturados mas veces");
        jpanelMostrar.add(jrbMostrarFacturadosMasVeces);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSustituir.setText("Sustituir");
        jbSustituir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSustituirActionPerformed(evt);
            }
        });

        jbFacturar.setText("Facturar");
        jbFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFacturarActionPerformed(evt);
            }
        });

        jbBuscarFactura.setText("Buscar Facura");
        jbBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarFacturaActionPerformed(evt);
            }
        });

        jTMaterial.setAutoCreateRowSorter(true);
        jTMaterial.setModel(albaranTableModel);
        jTMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMaterialMouseClicked(evt);
            }
        });
        jTMaterial.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTMaterialInputMethodTextChanged(evt);
            }
        });
        jSPMaterial.setViewportView(jTMaterial);
        //jTMaterial.getColumnModel().getColumn(0).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(1).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(2).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(3).setWidth(1000);
        //jTMaterial.updateUI();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jSPMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(jbEliminar)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSustituir)
                    .addComponent(jbFacturar)
                    .addComponent(jbBuscarFactura))
                .addGap(95, 95, 95))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlIdalbaran, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jtfIdalbaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlIdproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jtfFechaDesdeDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlObra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jtfObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jtfReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbBuscar)
                    .addGap(5, 5, 5)
                    .addComponent(jbNuevo)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jtfIdproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jtfFechaDesdeMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(368, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jtfFechaDesdeAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jlFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jtfFechaHastaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jtfFechaHastaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jtfFechaHastaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(416, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(276, Short.MAX_VALUE)
                    .addComponent(jbEditar)
                    .addGap(187, 187, 187)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpanelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jSPMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jbEliminar)
                .addGap(147, 147, 147)
                .addComponent(jbSustituir)
                .addGap(99, 99, 99)
                .addComponent(jbFacturar)
                .addGap(99, 99, 99)
                .addComponent(jbBuscarFactura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlIdalbaran))
                        .addComponent(jtfIdalbaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addComponent(jlIdproveedor)
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlFechaDesde))
                        .addComponent(jtfFechaDesdeDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlObra))
                        .addComponent(jtfObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlReceptor))
                        .addComponent(jtfReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(161, 161, 161)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbBuscar)
                        .addComponent(jbNuevo))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addComponent(jtfIdproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(229, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jtfFechaDesdeMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(199, Short.MAX_VALUE)
                    .addComponent(jtfFechaDesdeAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(181, 181, 181)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(189, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jlFechaHasta))
                        .addComponent(jtfFechaHastaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(171, 171, 171)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(jtfFechaHastaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(266, Short.MAX_VALUE)
                    .addComponent(jtfFechaHastaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(171, 171, 171)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(227, Short.MAX_VALUE)
                    .addComponent(jbEditar)
                    .addGap(207, 207, 207)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpanelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int locX, locY, sizeX, sizeY;
        sizeX = 300;
        sizeY = 20;
        this.jlIdalbaran.setSize(sizeX, sizeY);
        this.jlIdproveedor.setSize(sizeX, sizeY);
        this.jlFechaDesde.setSize(sizeX, sizeY);
        this.jlFechaHasta.setSize(sizeX, sizeY);
        this.jlObra.setSize(sizeX, sizeY);
        this.jlReceptor.setSize(sizeX, sizeY);
        
        this.jtfIdalbaran.setSize(sizeX, sizeY);
        this.jtfIdproveedor.setSize(sizeX, sizeY);
        this.jtfObra.setSize(sizeX, sizeY);
        this.jtfReceptor.setSize(sizeX, sizeY);
        
        locX = 10;
        locY = 10;
        this.jlIdalbaran.setLocation(locX, locY);
        locY+=this.jlIdalbaran.getHeight();
        this.jlIdproveedor.setLocation(locX, locY);
        locY+=this.jlIdproveedor.getHeight();
        this.jlFechaDesde.setLocation(locX, locY);
        locY+=this.jlFechaDesde.getHeight();
        this.jlObra.setLocation(locX, locY);
        locY+=this.jlObra.getHeight();
        this.jlReceptor.setLocation(locX, locY);
        locY+=this.jlReceptor.getHeight();
        
        locY+=10;
        this.jpanelMostrar.setLocation(locX, locY);
        locY+=this.jpanelMostrar.getHeight();
        locY+=10;
        
        System.out.println(this.jpanelMostrar.getHeight());
        
        this.jbBuscar.setLocation(locX, locY);
        locY+=this.jbBuscar.getHeight();
        
        locX = jbBuscar.getWidth()+20;
        locY = 10;
        this.jtfIdalbaran.setLocation(locX, locY);
        locY+=this.jtfIdalbaran.getHeight();
        this.jtfIdproveedor.setLocation(locX, locY);
        locY+=this.jtfIdproveedor.getHeight();
        this.jtfFechaDesdeDia.setLocation(locX, locY);
        locX += jtfFechaDesdeDia.getWidth() + 5;
        this.jtfFechaDesdeMes.setLocation(locX, locY);
        locX += jtfFechaDesdeMes.getWidth() + 5;
        this.jtfFechaDesdeAnio.setLocation(locX, locY);
        
        locX = jtfIdproveedor.getLocation().x + jtfIdproveedor.getWidth() - jtfFechaHastaAnio.getWidth();
        this.jtfFechaHastaAnio.setLocation(locX, locY);
        locX -= jtfFechaHastaMes.getWidth() + 5;
        this.jtfFechaHastaMes.setLocation(locX, locY);        
        locX -= jtfFechaHastaDia.getWidth() + 5;
        this.jtfFechaHastaDia.setLocation(locX, locY);
        locX -= jlFechaHasta.getPreferredSize().width + 10;
        this.jlFechaHasta.setLocation(locX, locY);
        
        locX = jbBuscar.getLocation().x + jbBuscar.getWidth()+10;
                
        locY+=this.jtfFechaDesdeDia.getHeight();
        this.jtfObra.setLocation(locX, locY);
        locY+=this.jtfObra.getHeight();
        this.jtfReceptor.setLocation(locX, locY);
        locY+=this.jtfReceptor.getHeight();
        
        
        locY=jbBuscar.getLocation().y;
        
        this.jbNuevo.setLocation(locX, locY);
        locX += jbNuevo.getWidth()+10;
        this.jbEditar.setLocation(locX, locY);
        locX += jbEditar.getWidth()+10;
        this.jbEliminar.setLocation(locX, locY);
        locX += jbEliminar.getWidth()+10;
        this.jbSustituir.setLocation(locX, locY);
        locX += jbSustituir.getWidth()+10;
        this.jbFacturar.setLocation(locX, locY);
        locX += jbFacturar.getWidth()+10;
        this.jbBuscarFactura.setLocation(locX, locY);
        
        
        locY+=this.jbNuevo.getHeight();
        
        
        
        locX=10;
        locY+=10;
        this.jSPMaterial.setLocation(locX, locY);
        this.jSPMaterial.setSize(this.getWidth()-2*locX,this.getHeight()-locY-40);
        this.jTMaterial.getColumnModel().getColumn(0).setPreferredWidth(this.getWidth()/6);
        this.jTMaterial.getColumnModel().getColumn(1).setPreferredWidth(this.getWidth()/6);
        this.jTMaterial.getColumnModel().getColumn(2).setPreferredWidth(this.getWidth()/6);
        this.jTMaterial.getColumnModel().getColumn(3).setPreferredWidth(this.getWidth()/6);
        this.jTMaterial.getColumnModel().getColumn(4).setPreferredWidth(this.getWidth()/6);
        this.jTMaterial.getColumnModel().getColumn(5).setPreferredWidth(this.getWidth()/6);
        this.jTMaterial.getColumnModel().getColumn(0).sizeWidthToFit();  
    }//GEN-LAST:event_formComponentResized

    private Vector getAlbaranFacturado(Vector vAlbaran, int type) {
        String sql;
        Statement statement;
        ResultSet resultSet;
        Vector vAlbaranFacturado;
        Albaran albaran;
        
        vAlbaranFacturado = new Vector();
        
        try {
            statement = connection.createStatement();
            for(int i=0;i<vAlbaran.size();i++) {
                albaran = (Albaran)vAlbaran.elementAt(i);
            
                sql = "SELECT * FROM ALBARAN_FACTURA WHERE ID_PROVEEDOR = '" +
                      albaran.getId_proveedor() +
                      "' AND ID_ALBARAN = '" +
                      albaran.getId_albaran() +
                      "';";
//                System.out.println(sql);    

                resultSet = statement.executeQuery(sql);
                
                
                
                if(resultSet.next()) {
                    if(type==0) { //Facturado
                        vAlbaranFacturado.addElement(albaran);
                    }
                } else if(type==1) { //No Facturado 
                    vAlbaranFacturado.addElement(albaran);
                } else if(type==2) { //Facturado solo 1 vez
                    if(!resultSet.next()) {
                       vAlbaranFacturado.addElement(albaran);
                    }
                } else if(type==3) {//Facturado 2 o mas veces
                    if(resultSet.next()) {
                       vAlbaranFacturado.addElement(albaran);
                    }
                }
            }
            statement.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        return vAlbaranFacturado;
        
    }
    
    
    
    private boolean isAlbaranFacturado(Albaran albaran) {
        String sql;
        Statement statement;
        ResultSet resultSet;
        
        try {
            sql = "SELECT * FROM ALBARAN_FACTURA WHERE ID_PROVEEDOR = '" +
                  albaran.getId_proveedor() +
                  "' AND ID_ALBARAN = '" +
                  albaran.getId_albaran() +
                  "';";
//            System.out.println(sql);    
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            return resultSet.next();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
        
    }
    
    private void buscar() {
        String sql, sql2;
        Statement statement;
        ResultSet resultSet;
        Albaran albaran;
        boolean noFecha;
        int diaDesde, mesDesde, anioDesde, diaHasta, mesHasta, anioHasta;
        Vector vAlbaran;

        albaranTableModel.clearTable();
        
        noFecha = jtfFechaDesdeDia.getText().trim().equals("") &&
                      jtfFechaDesdeMes.getText().trim().equals("") &&
                      jtfFechaDesdeAnio.getText().trim().equals("") &&
                      jtfFechaHastaDia.getText().trim().equals("") &&
                      jtfFechaHastaMes.getText().trim().equals("") &&
                      jtfFechaHastaAnio.getText().trim().equals("");
            
        if(!noFecha) {
            if(UtilGestion.getStringFecha(jtfFechaDesdeDia.getText().trim(), jtfFechaDesdeMes.getText().trim(), jtfFechaDesdeAnio.getText().trim())==null) {
//                System.out.println(jtfFechaDesdeDia.getText().trim()+"/"+jtfFechaDesdeMes.getText().trim()+"/"+jtfFechaDesdeAnio.getText().trim());
                javax.swing.JOptionPane.showMessageDialog(this, "Alguna de las fechas son incorrectas");
                return;
            }
            if(UtilGestion.getStringFecha(jtfFechaHastaDia.getText().trim(), jtfFechaHastaMes.getText().trim(), jtfFechaHastaAnio.getText().trim())==null) {
//                System.out.println(jtfFechaHastaDia.getText().trim()+"/"+jtfFechaHastaMes.getText().trim()+"/"+jtfFechaHastaAnio.getText().trim());
                javax.swing.JOptionPane.showMessageDialog(this, "Alguna de las fechas son incorrectas");
                return;
            }
        }
        
        sql2 = new String();
        if(!jtfIdalbaran.getText().trim().equals("")) {
            sql2 += "ID_ALBARAN LIKE '%" + jtfIdalbaran.getText().trim() + "%'";
        }
        
        if(!jtfIdproveedor.getText().trim().equals("")) {
            if(!sql2.equals(""))
                sql2 += " AND ";
            sql2 += "ID_PROVEEDOR LIKE '%" + jtfIdproveedor.getText().trim() + "%'";
        }
        
        if(!jtfObra.getText().trim().equals("")) {
            if(!sql2.equals(""))
                sql2 += " AND ";
            sql2 += "OBRA LIKE '%" + jtfObra.getText().trim() + "%'";
        }
        
        if(!jtfReceptor.getText().trim().equals("")) {
            if(!sql2.equals(""))
                sql2 += " AND ";
            sql2 += "RECEPTOR LIKE '%" + jtfReceptor.getText().trim() + "%'";
        }
        
        if(sql2.trim().equals(""))
            sql = "SELECT * FROM ALBARAN;";
        else {
            sql = "SELECT * FROM ALBARAN WHERE ";
            sql += sql2;
        }
        
        try {
            if(!noFecha) {
                diaDesde = Integer.parseInt(jtfFechaDesdeDia.getText().trim());
                mesDesde = Integer.parseInt(jtfFechaDesdeMes.getText().trim());
                anioDesde = Integer.parseInt(jtfFechaDesdeAnio.getText().trim());
                diaHasta = Integer.parseInt(jtfFechaHastaDia.getText().trim());
                mesHasta = Integer.parseInt(jtfFechaHastaMes.getText().trim());
                anioHasta = Integer.parseInt(jtfFechaHastaAnio.getText().trim());
            } else {
                diaDesde = 0;
                mesDesde = 0;
                anioDesde = 0;
                diaHasta = 0;
                mesHasta = 0;
                anioHasta = 0;
            }
            
            System.out.println(sql);
                
            vAlbaran = new Vector();
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while(resultSet.next()) {
                albaran = new Albaran();
                albaran.setId_albaran(resultSet.getString("ID_ALBARAN"));
                albaran.setId_proveedor(resultSet.getString("ID_PROVEEDOR"));
                albaran.setComentario(resultSet.getString("COMENTARIO"));
                albaran.setDescuento(resultSet.getDouble("DESCUENTO"));
                albaran.setObra(resultSet.getString("OBRA"));
                albaran.setReceptor(resultSet.getString("RECEPTOR"));
                albaran.setFecha(new Fecha(resultSet.getInt("DIA"),
                                 resultSet.getInt("MES"),
                                 resultSet.getInt("ANIO")));
                if(noFecha || albaran.isInFecha(diaDesde, mesDesde, anioDesde, diaHasta, mesHasta, anioHasta)) {
                    vAlbaran.addElement(albaran);
//                    if(jrbMostrarTodos.isSelected()) {
//                        albaranTableModel.addAlbaran(albaran);
//                    } 
//                    else if(jrbMostrarFacturados.isSelected()) {
//                        if(isAlbaranFacturado(albaran)) {
//                            albaranTableModel.addAlbaran(albaran);
//                        }
//                    } else if(jrbMostrarNoFacturados.isSelected()) {
//                        if(!isAlbaranFacturado(albaran)) {
//                            albaranTableModel.addAlbaran(albaran);
//                        }
//                    }
                }
            }
            
            if(jrbMostrarFacturados.isSelected()) {
                vAlbaran = getAlbaranFacturado(vAlbaran,0);
            } else if(jrbMostrarNoFacturados.isSelected()) {
                vAlbaran = getAlbaranFacturado(vAlbaran,1);
            } else if(jrbMostrarFacturados1Vez.isSelected()) {
                vAlbaran = getAlbaranFacturado(vAlbaran,2);
            } else if(jrbMostrarFacturadosMasVeces.isSelected()) {
                vAlbaran = getAlbaranFacturado(vAlbaran,3);
            }
            
            
            
            for(int i=0;i<vAlbaran.size();i++) {
                albaran = (Albaran)vAlbaran.elementAt(i);
                albaranTableModel.addAlbaran(albaran);
            }
            
            jTMaterial.updateUI();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    
    private void jTMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMaterialMouseClicked
//        this.jTMaterial.getCellEditor(WIDTH, WIDTH);
//        System.out.println(this.jTMaterial.columnAtPoint(evt.getPoint()));
    }//GEN-LAST:event_jTMaterialMouseClicked

    private void jTMaterialInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTMaterialInputMethodTextChanged
//        System.out.println("");
    }//GEN-LAST:event_jTMaterialInputMethodTextChanged

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        JFormAlbaranEditor jFormAlbaranEditor = new JFormAlbaranEditor(parent,true);
        jFormAlbaranEditor.setConnection(connection);
        jFormAlbaranEditor.setNewAlbaran(true);
        jFormAlbaranEditor.setVisible(true);
        this.jTMaterial.updateUI();
}//GEN-LAST:event_jbNuevoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        Albaran albaran;
        int row;
        JFormAlbaranEditor jFormAlbaranEditor = new JFormAlbaranEditor(parent,true);
        
        
        row = jTMaterial.getSelectedRow();
        row = jTMaterial.convertRowIndexToModel(row);
        albaran = albaranTableModel.getAlbaran(row);
        if(albaran!=null) {
            jFormAlbaranEditor.setConnection(connection);
            jFormAlbaranEditor.setAlbaran(albaran);
            jFormAlbaranEditor.setNewAlbaran(false);
            jFormAlbaranEditor.setVisible(true);
            buscar();
            this.jTMaterial.updateUI();
        } else {
            JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada");
        }        
}//GEN-LAST:event_jbEditarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        Albaran albaran;
        int row;
        JFormAlbaranEditor jFormAlbaranEditor = new JFormAlbaranEditor(parent,true);
        int option;
        String sql;
        Statement statement;
        
        
        row = jTMaterial.getSelectedRow();
        if(row<0)
            return;
        row = jTMaterial.convertRowIndexToModel(row);
        albaran = albaranTableModel.getAlbaran(row);
        if(albaran!=null) {
            option = javax.swing.JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar el albarán "+albaran.getId_albaran()+"?");
            if(option == javax.swing.JOptionPane.YES_OPTION) {
                sql = "DELETE FROM MATERIAL_ALBARAN WHERE ID_PROVEEDOR='" +
                      albaran.getId_proveedor() +
                      "' AND ID_ALBARAN='" +
                      albaran.getId_albaran() +
                      "';";
                try {
                    statement = connection.createStatement();
                    statement.executeUpdate(sql);
                    sql = "DELETE FROM ALBARAN WHERE ID_PROVEEDOR='" +
                          albaran.getId_proveedor() +
                          "' AND ID_ALBARAN='" +
                          albaran.getId_albaran() +
                          "';";
                    statement.executeUpdate(sql);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            buscar();
            this.jTMaterial.updateUI();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada");
        }     
}//GEN-LAST:event_jbEliminarActionPerformed

    private void jbSustituirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSustituirActionPerformed
        Albaran albaran;
        int row;
        JFormAlbaranIdEditor jFormAlbaranIdEditor = new JFormAlbaranIdEditor(parent,true);
        
        
        row = jTMaterial.getSelectedRow();
        row = jTMaterial.convertRowIndexToModel(row);
        albaran = albaranTableModel.getAlbaran(row);
        if(albaran!=null) {
            jFormAlbaranIdEditor.setConnection(connection);
            jFormAlbaranIdEditor.setAlbaran(albaran);
            jFormAlbaranIdEditor.setVisible(true);
            buscar();
            this.jTMaterial.updateUI();
        } else {
            JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada");
        }        
}//GEN-LAST:event_jbSustituirActionPerformed

    private void jbFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFacturarActionPerformed
        int[] selectedRows;
        Albaran albaran;
        JFormFacturaEditor jFormFacturaEditor = new JFormFacturaEditor(parent,true);
        
        jFormFacturaEditor.setConnection(connection);
        jFormFacturaEditor.setNewFactura(true);
        
        selectedRows = jTMaterial.getSelectedRows();
        
        for(int i=0;i<selectedRows.length;i++) {
            int j;
            j= jTMaterial.convertRowIndexToModel(selectedRows[i]);
            albaran = albaranTableModel.getAlbaran(j);
            jFormFacturaEditor.añadirAlbaran(albaran);
            System.out.println(albaran.getId_albaran());
        }
        
        jFormFacturaEditor.setVisible(true);
        this.jTMaterial.updateUI();
}//GEN-LAST:event_jbFacturarActionPerformed

    private void jbBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarFacturaActionPerformed
        JFormAlbaranFactura jFormAlbaranFactura;
        int row;
        Albaran albaran;
        
        row = jTMaterial.getSelectedRow();
        if(row<0)
            return;
        
        row = jTMaterial.convertRowIndexToModel(row);
        albaran = albaranTableModel.getAlbaran(row);
        
        
        jFormAlbaranFactura = new JFormAlbaranFactura(null,true);
        jFormAlbaranFactura.setConnection(connection);
        jFormAlbaranFactura.setAlbaran(albaran);
        jFormAlbaranFactura.setVisible(true);
        
        
}//GEN-LAST:event_jbBuscarFacturaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormAlbaran(null,true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMostrar;
    private javax.swing.JScrollPane jSPMaterial;
    private javax.swing.JTable jTMaterial;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbBuscarFactura;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbFacturar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSustituir;
    private javax.swing.JLabel jlFechaDesde;
    private javax.swing.JLabel jlFechaHasta;
    private javax.swing.JLabel jlIdalbaran;
    private javax.swing.JLabel jlIdproveedor;
    private javax.swing.JLabel jlObra;
    private javax.swing.JLabel jlReceptor;
    private javax.swing.JPanel jpanelMostrar;
    private javax.swing.JRadioButton jrbMostrarFacturados;
    private javax.swing.JRadioButton jrbMostrarFacturados1Vez;
    private javax.swing.JRadioButton jrbMostrarFacturadosMasVeces;
    private javax.swing.JRadioButton jrbMostrarNoFacturados;
    private javax.swing.JRadioButton jrbMostrarTodos;
    private javax.swing.JTextField jtfFechaDesdeAnio;
    private javax.swing.JTextField jtfFechaDesdeDia;
    private javax.swing.JTextField jtfFechaDesdeMes;
    private javax.swing.JTextField jtfFechaHastaAnio;
    private javax.swing.JTextField jtfFechaHastaDia;
    private javax.swing.JTextField jtfFechaHastaMes;
    private javax.swing.JTextField jtfIdalbaran;
    private javax.swing.JTextField jtfIdproveedor;
    private javax.swing.JTextField jtfObra;
    private javax.swing.JTextField jtfReceptor;
    // End of variables declaration//GEN-END:variables
    
}
