/*
 * JFormMaterial.java
 *
 * Created on 11 de enero de 2008, 0:00
 */

package vgestion;

import javax.swing.table.TableColumnModel;
import java.sql.*;

/**
 *
 * @author  Juan Luis
 */
public class JFormProveedor extends javax.swing.JDialog {
    private java.awt.Frame parent;
    private ProveedorTableModel proveedorTableModel;
    private Connection connection;

    public Connection getConnection() {
        return connection;
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
        insertData();
    }
    
    /** Creates new form JFormMaterial */
    public JFormProveedor(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        this.parent = parent;
        proveedorTableModel = new ProveedorTableModel();
        initComponents();
    }
    
    private void insertData() {
        String sql;
        Statement statement;
        ResultSet resultSet;
        Proveedor proveedor;
        
        try {
            sql = "SELECT * FROM PROVEEDOR;";
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            while(resultSet.next()) {
                proveedor = new Proveedor();
                proveedor.setCif(resultSet.getString("CIF"));
                proveedor.setCp(resultSet.getString("CP"));
                proveedor.setDireccion(resultSet.getString("DIRECCION"));
                proveedor.setId_proveedor(resultSet.getString("ID_PROVEEDOR"));
                proveedor.setNombre(resultSet.getString("NOMBRE"));
                proveedor.setPoblacion(resultSet.getString("POBLACION"));
                proveedor.setTelefono(resultSet.getString("TELEFONO"));
                proveedorTableModel.addProveedor(proveedor);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        jtProveedor.updateUI();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNew = new javax.swing.JButton();
        jspProveedor = new javax.swing.JScrollPane();
        jtProveedor = new javax.swing.JTable();

        setTitle("Proveedores");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jbNew.setText("Nuevo proveedor");
        jbNew.setPreferredSize(new java.awt.Dimension(200, 20));
        jbNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewActionPerformed(evt);
            }
        });

        jtProveedor.setAutoCreateRowSorter(true);
        jtProveedor.setEnabled(false);
        jtProveedor.setModel(proveedorTableModel);
        jtProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProveedorMouseClicked(evt);
            }
        });
        jtProveedor.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtProveedorInputMethodTextChanged(evt);
            }
        });
        jspProveedor.setViewportView(jtProveedor);
        //jTMaterial.getColumnModel().getColumn(0).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(1).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(2).setWidth(1);
        //jTMaterial.getColumnModel().getColumn(3).setWidth(1000);
        //jTMaterial.updateUI();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jspProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbNew, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int locX, locY;
        
        locX = 10;
        locY = 10;
        
        this.jbNew.setLocation(this.getWidth()/2-100, locY);
        this.jbNew.setSize(200,25);
        
        locY += 40;
       
        this.jspProveedor.setLocation(locX, locY);
        this.jspProveedor.setSize(this.getWidth()-2*locX,this.getHeight()-locY-40);
        this.jtProveedor.getColumnModel().getColumn(0).setPreferredWidth(100);
        this.jtProveedor.getColumnModel().getColumn(1).setPreferredWidth(100);
        this.jtProveedor.getColumnModel().getColumn(3).setPreferredWidth(100);
        this.jtProveedor.getColumnModel().getColumn(4).setPreferredWidth(100);
        this.jtProveedor.getColumnModel().getColumn(5).setPreferredWidth(100);
        this.jtProveedor.getColumnModel().getColumn(6).setPreferredWidth(100);
        this.jtProveedor.getColumnModel().getColumn(2).setPreferredWidth(this.getWidth()-600);
        this.jtProveedor.getColumnModel().getColumn(0).sizeWidthToFit();
        
       
        
//        this.jBNuevo.setLocation(this.getWidth()/2-this.jBNuevo.getWidth(), 0);
    }//GEN-LAST:event_formComponentResized

    private void jtProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProveedorMouseClicked
//        this.jTMaterial.getCellEditor(WIDTH, WIDTH);
//        System.out.println(this.jTMaterial.columnAtPoint(evt.getPoint()));
}//GEN-LAST:event_jtProveedorMouseClicked

    private void jtProveedorInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtProveedorInputMethodTextChanged
//        System.out.println("");
}//GEN-LAST:event_jtProveedorInputMethodTextChanged

    private void jbNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewActionPerformed
        JFormProveedorEditor jFormProveedorEditor = new JFormProveedorEditor(parent,true);
        jFormProveedorEditor.setConnection(connection);
        jFormProveedorEditor.setVisible(true);
        proveedorTableModel.clearAll();
        insertData();
    }//GEN-LAST:event_jbNewActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormProveedor(null,true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbNew;
    private javax.swing.JScrollPane jspProveedor;
    private javax.swing.JTable jtProveedor;
    // End of variables declaration//GEN-END:variables
    
}
