/*
 * JFormMaterialLista.java
 *
 * Created on 4 de septiembre de 2008, 23:16
 */

package vgestion;

import java.sql.*;
import java.util.Vector;

/**
 *
 * @author  Juan Luis
 */
public class JFormMaterialLista extends javax.swing.JDialog {
    private Material material;
    private Connection connection;
    private boolean canceled;
    Vector vMateriales;

    public void setIdMaterial(String idMaterial) {
        jtfIdmaterial.setText(idMaterial);
    }

    public void setIdProveedor(String idProveedor) {
        jtfIdproveedor.setText(idProveedor);
    }
    

    public boolean isCanceled() {
        return canceled;
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
    }

    public Material getMaterial() {
        return material;
    }
    
    
    /** Creates new form JFormMaterialLista */
    public JFormMaterialLista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        vMateriales = new Vector();
        initComponents();
        
        jlistListaMateriales.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { 
                return vMateriales.size(); 
            }
            public Object getElementAt(int i) { 
                Material material;
                material = (Material)vMateriales.elementAt(i);
                return material.getId_material() + "  " + material.getDescripcion(); 
            }
        });
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jlIdproveedor = new javax.swing.JLabel();
        jtfIdproveedor = new javax.swing.JTextField();
        jlIdmaterial = new javax.swing.JLabel();
        jtfIdmaterial = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jspListaMateriales = new javax.swing.JScrollPane();
        jlistListaMateriales = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Material"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jlIdproveedor.setText("Id Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlIdproveedor, gridBagConstraints);

        jtfIdproveedor.setEnabled(false);
        jtfIdproveedor.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIdproveedor.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel1.add(jtfIdproveedor, gridBagConstraints);

        jlIdmaterial.setText("Id Material");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlIdmaterial, gridBagConstraints);

        jtfIdmaterial.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIdmaterial.setPreferredSize(new java.awt.Dimension(400, 20));
        jtfIdmaterial.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtfIdmaterialPropertyChange(evt);
            }
        });
        jtfIdmaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdmaterialKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel1.add(jtfIdmaterial, gridBagConstraints);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jbBuscar, gridBagConstraints);

        jlistListaMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlistListaMaterialesMousePressed(evt);
            }
        });
        jspListaMateriales.setViewportView(jlistListaMateriales);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        jPanel1.add(jspListaMateriales, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(jbAceptar);

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jbCancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed

        if(jlistListaMateriales.getSelectedIndex()<0) {
            canceled = true;
            dispose();
            return;
        }
        material = (Material)vMateriales.elementAt(jlistListaMateriales.getSelectedIndex());
        dispose();
        
        
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        material = null;
        canceled = true;
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        buscarMateriales(jtfIdmaterial.getText().trim(), jtfIdproveedor.getText().trim());
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        buscarMateriales(jtfIdmaterial.getText().trim(), jtfIdproveedor.getText().trim());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jlistListaMaterialesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistListaMaterialesMousePressed
        if(evt.getClickCount()>1) {
            material = (Material)vMateriales.elementAt(jlistListaMateriales.getSelectedIndex());
            dispose();
        }
    }//GEN-LAST:event_jlistListaMaterialesMousePressed

    private void jtfIdmaterialPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtfIdmaterialPropertyChange
//        if(connection!=null)
//            buscarMateriales(jtfIdmaterial.getText().trim(), jtfIdproveedor.getText().trim());
    }//GEN-LAST:event_jtfIdmaterialPropertyChange

    private void jtfIdmaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdmaterialKeyTyped
        if(evt.getKeyChar()=='\n')
            buscarMateriales(jtfIdmaterial.getText().trim(), jtfIdproveedor.getText().trim());
    }//GEN-LAST:event_jtfIdmaterialKeyTyped
    
    private void buscarMateriales(String idMaterial, String idProveedor) {
        String sql;
        Statement statement ;
        ResultSet resultSet;
        Material temp;
        
        sql = "SELECT * FROM MATERIAL WHERE ID_PROVEEDOR = '" +
              idProveedor +
              "' AND ID_MATERIAL LIKE '%" +
              idMaterial +
              "%'";
        
        System.out.println(sql);
        
        try {
            statement = this.connection.createStatement();
            resultSet = statement.executeQuery(sql);
            vMateriales = new Vector();
            while(resultSet.next()) {
                temp = new Material();
                temp.setId_material(resultSet.getString("ID_MATERIAL"));
                temp.setDescripcion(resultSet.getString("DESCRIPCION"));
                vMateriales.addElement(temp);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Database error");
            e.printStackTrace();
            return;
        }
        jlistListaMateriales.updateUI();
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFormMaterialLista dialog = new JFormMaterialLista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlIdmaterial;
    private javax.swing.JLabel jlIdproveedor;
    private javax.swing.JList jlistListaMateriales;
    private javax.swing.JScrollPane jspListaMateriales;
    private javax.swing.JTextField jtfIdmaterial;
    private javax.swing.JTextField jtfIdproveedor;
    // End of variables declaration//GEN-END:variables
    
}
