/*
 * JFormMaterialEditor.java
 *
 * Created on 12 de enero de 2008, 20:30
 */

package vgestion;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author  Juan Luis
 */
public class JFormMaterialIdEditor extends javax.swing.JDialog {
    private Material material;
    private Connection connection;
    
    /** Creates new form JFormMaterialEditor */
    
    public JFormMaterialIdEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        material = new Material();
        initComponents();
    }

    public Connection getConnection() {
        return connection;
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
    }
    
    public void setId_proveedor(String id_proveedor) {
        jtfIdproveedor.setText(id_proveedor);
        jtfIdproveedor.setEditable(false);
    }
    
    public void setId_material(String id_material) {
        jtfIdmaterial.setText(id_material);
        jtfIdmaterial.setEditable(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jlIdmaterial = new javax.swing.JLabel();
        jtfIdmaterial = new javax.swing.JTextField();
        jlIdproveedor = new javax.swing.JLabel();
        jtfIdproveedor = new javax.swing.JTextField();
        jlMarca = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jlRefMarca = new javax.swing.JLabel();
        jtfRefMarca = new javax.swing.JTextField();
        jlDescripcion = new javax.swing.JLabel();
        jtfDescripcion = new javax.swing.JTextField();
        jlCategoria = new javax.swing.JLabel();
        jtfCategoria = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Editor de materiales");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Material"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jlIdmaterial.setText("Id Material");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlIdmaterial, gridBagConstraints);

        jtfIdmaterial.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIdmaterial.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(jtfIdmaterial, gridBagConstraints);

        jlIdproveedor.setText("Id Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlIdproveedor, gridBagConstraints);

        jtfIdproveedor.setEditable(false);
        jtfIdproveedor.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfIdproveedor.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(jtfIdproveedor, gridBagConstraints);

        jlMarca.setText("Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlMarca, gridBagConstraints);

        jtfMarca.setEditable(false);
        jtfMarca.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfMarca.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(jtfMarca, gridBagConstraints);

        jlRefMarca.setText("Ref Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlRefMarca, gridBagConstraints);

        jtfRefMarca.setEditable(false);
        jtfRefMarca.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfRefMarca.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(jtfRefMarca, gridBagConstraints);

        jlDescripcion.setText("Descripcion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlDescripcion, gridBagConstraints);

        jtfDescripcion.setEditable(false);
        jtfDescripcion.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfDescripcion.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(jtfDescripcion, gridBagConstraints);

        jlCategoria.setText("Categoria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jlCategoria, gridBagConstraints);

        jtfCategoria.setEditable(false);
        jtfCategoria.setMinimumSize(new java.awt.Dimension(400, 20));
        jtfCategoria.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(jtfCategoria, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(jbAceptar);

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jbCancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        String sql;
        Statement statement ;
        ResultSet resultSet;
        
        
        sql = "SELECT * FROM PROVEEDOR WHERE ID_PROVEEDOR = '" +
              jtfIdproveedor.getText().trim() +
              "';";
        
        try {
            statement = this.connection.createStatement();
            resultSet = statement.executeQuery(sql);
            if(!resultSet.next()) {
                javax.swing.JOptionPane.showMessageDialog(this,"Proveedor no encontrado");
                return;
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Database error");
            return;
        }
        
        if(jtfIdmaterial.getText().trim().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,"Id de material incorrecto");
            return;
        }
        
        
        sql = "SELECT * FROM MATERIAL WHERE ID_PROVEEDOR = '" +
              jtfIdproveedor.getText().trim() +
              "' AND ID_MATERIAL = '" +
              jtfIdmaterial.getText().trim() +
              "';";
        try {
            statement = this.connection.createStatement();
            resultSet = statement.executeQuery(sql);
            if(resultSet.next()) {
                if(JOptionPane.showConfirmDialog(this,"El material ya existe, ¿desea sustituirlo?","El material ya existe",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION)
                    return;
                sustituirMaterial(this.material.getId_material(),jtfIdmaterial.getText().trim(),jtfIdproveedor.getText().trim());
                borrarMaterial(material.getId_material(),material.getId_proveedor());
            } else {
                sustituirMaterial(this.material.getId_material(),jtfIdmaterial.getText().trim(),jtfIdproveedor.getText().trim());
                cambiarIdMaterial(this.material.getId_material(),jtfIdmaterial.getText().trim(),jtfIdproveedor.getText().trim());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Database error");
            e.printStackTrace();
            return;
        }
        
        
        this.dispose();
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        material = null;
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed
    
    private void cambiarIdMaterial(String idMaterialAntiguo, String idMaterialNuevo, String idProveedor) {
        String sql;
        Statement statement ;
        
        
        sql = "UPDATE MATERIAL SET ID_MATERIAL= '" +
              idMaterialNuevo +
              "' WHERE ID_PROVEEDOR = '" +
              idProveedor +
              "' AND ID_MATERIAL = '"+
              idMaterialAntiguo +
              "';";
        
        try {
            statement = this.connection.createStatement();
            statement.execute(sql);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Database error");
            return;
        }
        
    }
    
    private void sustituirMaterial(String idMaterialAntiguo, String idMaterialNuevo, String idProveedor) {
        String sql;
        Statement statement ;
        
        
        sql = "UPDATE MATERIAL_ALBARAN SET ID_MATERIAL= '" +
              idMaterialNuevo +
              "' WHERE ID_PROVEEDOR = '" +
              idProveedor +
              "' AND ID_MATERIAL = '"+
              idMaterialAntiguo +
              "';";
        
        try {
            statement = this.connection.createStatement();
            statement.execute(sql);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Database error");
            return;
        }
        
    }
    
    private void borrarMaterial(String idMaterial, String idProveedor) {
        String sql;
        Statement statement ;
        
        
        sql = "DELETE FROM MATERIAL WHERE ID_PROVEEDOR = '" +
              idProveedor +
              "' AND ID_MATERIAL = '" +
              idMaterial +
              "';";
        try {
            statement = this.connection.createStatement();
            statement.executeUpdate(sql);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Database error");
            e.printStackTrace();
            return;
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFormMaterialIdEditor dialog = new JFormMaterialIdEditor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
        setTitle("Sustituir material "+ material.getId_material());
        jtfIdmaterial.setText(material.getId_material());
        jtfIdproveedor.setText(material.getId_proveedor());
        jtfCategoria.setText(material.getCategoria());
        jtfDescripcion.setText(material.getDescripcion());
        jtfMarca.setText(material.getMarca());
        jtfRefMarca.setText(material.getRef_marca());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlDescripcion;
    private javax.swing.JLabel jlIdmaterial;
    private javax.swing.JLabel jlIdproveedor;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlRefMarca;
    private javax.swing.JTextField jtfCategoria;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfIdmaterial;
    private javax.swing.JTextField jtfIdproveedor;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfRefMarca;
    // End of variables declaration//GEN-END:variables
    
}
