/*
 * JFramePrincipal.java
 *
 * Created on 10 de enero de 2008, 23:48
 */

package vgestion;
import java.sql.*;
/**
 *
 * @author  Juan Luis
 */
public class JFramePrincipal extends javax.swing.JFrame {
    private Connection connection;
    /** Creates new form JFramePrincipal */
    public JFramePrincipal(String databaseFilePath) {
        initComponents();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");//Loading Driver
            String connectionUrl = "jdbc:ucanaccess://"+databaseFilePath;
            connection= DriverManager.getConnection(connectionUrl);
            if(connection == null){
                System.out.println("No se ha podido establecer la conexión");
            }else{
                System.out.println("La conexión fue un éxito");
                }
        }catch(Exception e){ 
            System.out.println("Error a la hora de establecer la conexión"); 
            System.out.println(e); 
            this.dispose();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbMaterial = new javax.swing.JButton();
        jbProveedor = new javax.swing.JButton();
        jbAlbaran = new javax.swing.JButton();
        jbFactura = new javax.swing.JButton();
        jbHistorialPrecios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa de gestión de compras");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(2, 3));

        jbMaterial.setText("Materiales");
        jbMaterial.setActionCommand("jBMaterial");
        jbMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(jbMaterial);

        jbProveedor.setText("Proveedores");
        jbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(jbProveedor);

        jbAlbaran.setText("Albaranes");
        jbAlbaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlbaranActionPerformed(evt);
            }
        });
        getContentPane().add(jbAlbaran);

        jbFactura.setText("Facturas");
        jbFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(jbFactura);

        jbHistorialPrecios.setText("Historial precio");
        jbHistorialPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHistorialPreciosActionPerformed(evt);
            }
        });
        getContentPane().add(jbHistorialPrecios);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMaterialActionPerformed
        JFormMaterial jFormMaterial = new JFormMaterial(this,true);
        jFormMaterial.setConnection(connection);
        jFormMaterial.setVisible(true);
}//GEN-LAST:event_jbMaterialActionPerformed

    private void jbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProveedorActionPerformed
        JFormProveedor jFormProveedor = new JFormProveedor(this,true);
        jFormProveedor.setConnection(connection);
        jFormProveedor.setVisible(true);
    }//GEN-LAST:event_jbProveedorActionPerformed

    private void jbAlbaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlbaranActionPerformed
        JFormAlbaran jFormAlbaran = new JFormAlbaran(this,true);
        jFormAlbaran.setConnection(connection);
        jFormAlbaran.setVisible(true);
}//GEN-LAST:event_jbAlbaranActionPerformed

    private void jbHistorialPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHistorialPreciosActionPerformed
        JFormHistorialMaterial jFormHistorialMaterial = new JFormHistorialMaterial(this,true);
        jFormHistorialMaterial.setConnection(connection);
        jFormHistorialMaterial.setVisible(true);
    }//GEN-LAST:event_jbHistorialPreciosActionPerformed

    private void jbFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFacturaActionPerformed
        JFormFactura jFormFactura = new JFormFactura(this,true);
        jFormFactura.setConnection(connection);
        jFormFactura.setVisible(true);
}//GEN-LAST:event_jbFacturaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (args.length!=1) {
            System.out.println("El sistema debe proporcionar un único parámetro: " +
                "La ruta del fichero que contiene la base de datos");
                System.exit(1);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFramePrincipal jFramePrincipal = new JFramePrincipal(args[0]);
                jFramePrincipal.setVisible(true);
            }
        });
    }
    
//    public void dispose() {
//        try {
//            this.connection.close();
//        } catch (Exception e) {
//            
//        }
//        super.dispose();
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlbaran;
    private javax.swing.JButton jbFactura;
    private javax.swing.JButton jbHistorialPrecios;
    private javax.swing.JButton jbMaterial;
    private javax.swing.JButton jbProveedor;
    // End of variables declaration//GEN-END:variables
    
}
